,Filter:,is:issue is:closed created:2023-10-20..2024-03-27 label:type:bug linked:pr,,,,,,
Issue #,PR #,Title,Reproduced,Buggy File(s),Buggy Function(s),Remarks,Issue Link,PR Link
63037,63092,tf.raw_ops.UnravelIndex can leads to eigen assertion failure,No,tensorflow/core/kernels/unravel_index_op.cc,UnravelIndexOp.Compute(),Did not attempt: general non-dnn bug,https://github.com/tensorflow/tensorflow/issues/63037,https://github.com/tensorflow/tensorflow/pull/63092
63036,63091,tf.raw_ops.Substr can lead to eigen assertion failure,No,tensorflow/core/kernels/substr_op.cc,SubstrOp.Compute(),Did not attempt: general non-dnn bug,https://github.com/tensorflow/tensorflow/issues/63036,https://github.com/tensorflow/tensorflow/pull/63091
63031,63050,Confusing result of tf.argsort/argmax/argmin/ given a boolean axis,No,tensorflow/python/ops/math_ops.py,argmax_v2(),Did not attempt: general non-dnn bug,https://github.com/tensorflow/tensorflow/issues/63031,https://github.com/tensorflow/tensorflow/pull/63050
63012,63083,Unit test failures with Python 3.12 and gcc,No,tensorflow/python/client/tf_session_wrapper.cc,PyGraphData.Clear(),Did not attempt: data structure specific bug,https://github.com/tensorflow/tensorflow/issues/63012,https://github.com/tensorflow/tensorflow/pull/63083
62981,63105,tf.raw_ops.DrawBoundingBoxesV2 aborts with inappropriate input,No,tensorflow/core/kernels/image/draw_bounding_box_op.cc,DrawBoundingBoxesOp.Compute(),Did not attempt: general non-dnn bug,https://github.com/tensorflow/tensorflow/issues/62981,https://github.com/tensorflow/tensorflow/pull/63105
62977,62990,tf.raw_ops.RecordInput aborts with negative batch_size,No,tensorflow/core/kernels/record_input_op.cc,RecordInputOp.GETATTR(),Did not attempt: general non-dnn bug,https://github.com/tensorflow/tensorflow/issues/62977,https://github.com/tensorflow/tensorflow/pull/62990
62882,62897,remapper_test fails on AARCH64 with --config=mkl_aarch64_threadpool,No,"tensorflow/core/grappler/optimizers/mkl_remapper_test.cc,tensorflow/core/grappler/optimizers/remapper_test.cc",Tests,Did not attempt: fixing tests,https://github.com/tensorflow/tensorflow/issues/62882,https://github.com/tensorflow/tensorflow/pull/62897
62835,62876,mkl_remapper_test fails with TF_ENABLE_ONEDNN_OPTS=1,No,"tensorflow/core/grappler/optimizers/mkl_remapper_test.c,tensorflow/core/grappler/optimizers/remapper_test.cc",Tests,Did not attempt: fixing tests,https://github.com/tensorflow/tensorflow/issues/62835,https://github.com/tensorflow/tensorflow/pull/62876
62549,7899,Inconsistency in XLA Cotionmpila with Operand Order Swap in tf.add with Specific Operators on GPU,Yes,https://github.com/openxla/xla/tree/main/xla/service/gpu/ir_emission_utils.cc,"FindTransposeHero, transpose",Reproduced: bug originates from the XLA compiler (not tensorflow repo),https://github.com/tensorflow/tensorflow/issues/62549,https://github.com/tensorflow/tensorflow/pull/7899
62492,62496,Python code modifies loop while iterating over it,No,tensorflow/python/training/saver.py,_RecordLastCheckpoint(),"Did not atttempt: bug found through reading code, not executing",https://github.com/tensorflow/tensorflow/issues/62492,https://github.com/tensorflow/tensorflow/pull/62496
62127,62128,Invalid classifier used for CUDA 12.2,No,tensorflow/tools/pip_package/setup.py,,Did not attempt: Related to pushing tf to pypi,https://github.com/tensorflow/tensorflow/issues/62127,https://github.com/tensorflow/tensorflow/pull/62128
62091,62139,NNAPI delegate crashes on kTfLiteBuiltinCos in TF Lite 2.14,No,tensorflow/lite/delegates/nnapi/nnapi_delegate.cc,TransformCosIntoSupportedOps(),Did not attempt: Requires a mobile device,https://github.com/tensorflow/tensorflow/issues/62091,https://github.com/tensorflow/tensorflow/pull/62139
62072,62112,tf.math.is_non_decreasing outputs incorrect result when input is an uint tensor,No,tensorflow/python/ops/check_ops.py,_get_results_for_monotonic_comparison(),Did not attempt: data structure specific bug,https://github.com/tensorflow/tensorflow/issues/62072,https://github.com/tensorflow/tensorflow/pull/62112
61974,61981,AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface',Yes,tensorflow/python/keras/engine/data_adapter.py,_is_distributed_dataset(),Reproduced: bug originates from reference to legacy code,https://github.com/tensorflow/tensorflow/issues/61974,https://github.com/tensorflow/tensorflow/pull/61981